apiVersion: v1
kind: Service
metadata:
  name: intel-llama-metrics
  labels:
    app.kubernetes.io/name: intel-llama
    app.kubernetes.io/instance: llm-serving
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: llm-serving
spec:
  selector:
    app.kubernetes.io/name: intel-llama
    app.kubernetes.io/instance: llm-serving
  ports:
    - name: metrics
      port: 80
      targetPort: http
      protocol: TCP
