apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: intel-llama-model-cache
  labels:
    app.kubernetes.io/name: intel-llama
    app.kubernetes.io/instance: llm-serving
    app.kubernetes.io/component: model-cache
    app.kubernetes.io/part-of: llm-serving
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
