apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: actions-runner-system
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: actions-runner-system
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: actions-runner
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actions-runner-secret-vault
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: actions-runner-secret-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: github_token
      remoteRef:
        key: services/github/actions-runner
        property: token
