---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: actions-runner-secret
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgAozAW+cY4aZI78w7/R4pJZ7QV61fb/MeQUCMyN8kc2BIBo9kVDwLz1ZXYdIf4dWi0G3X9DiTJJ8uckTyc2UmWfz9uoC9rx+yrtyCIZowqfzfPKBso+Mcnsl9uBLWHszcTlXPN1m3bQTJ1egDftEkY46uoqZxqfOMzEtYRLsMooMyeejTZ90746GAy78HL0xzoapgLaKWs9nCnCtIJALUTMFWWKJB8jyJss79Y/kUyxgAfe5a4/krB0CWnkADzCeSdADXR3IpYHXNKUKKGQwgSyR2MqxDa5UnrFGSoZ3ZDMPbpJVxve42wx3MzKeAYOcEXA5Nbivr6VRQ38mS7ziCAqlpCnudF8tsoUQkdQI2R5FvvdB/uJD71tiGF2Pd20cfZlnBcTbMbUYaJrt/adPcdAFgogjE2F1Qw5FQo20w1m+Se9VVYNgHkA2yPH1Has6nvzAIL0XV5Xp12tHdXWNX3sb/B0HgKKNCZ0ACqOdMlv7AI1y5/0wpXTKG6BplurPLpBWRWeYbnNZfvscQsGUUJtTEqZlSg/r0Au9HKiDJzMRMvZdpjJmwOvk9t9UQkgoRuojxL5+InrOa9hDsnnCP1Ynz5Rz5FIgBXBHS2w+3MlhJilXUQJCJ3wlFtK/7zHXfLDtK4ZZhkNdQrU5LBr0pzqzgc0FRQE43bLXLfvwO6c05c2SQBcHvDbyttKSRdfLHi57MriZAJfQVzF+JnZ3/Zb5U3owtmUxD1NKzjJQOaTPvo2cHaEVRON
  template:
    metadata:
      name: actions-runner-secret
      namespace: actions-runner-system
    type: Opaque

