---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: baskit
spec:
  encryptedData:
    .dockerconfigjson: AgB4VISBi3yNJ4FhhRLJZmgTnveNiVJqwlYEsrZa0lHj+PmQjiWQmG+iVh+5tIMcdBdyjEpX6b+sngOHMNHnoD0zpyHPNdbajHSB8q6N9emYMwwRS4QED3JDlQ0G5fdb4D4MbT/QkGEWd0I7reUo+c+a3oZFwobXHhq0Jzs6dLlSddIqY4JxKWnO9Jpw6hWy75KxF/eNrh6u/QCWvomDYrKzJAXq1r0+XqEwFyI3G31WKLnxPkWk20s8b0rExn4NaF1gRxDFXHjrcO85FZgTzbf4RqDKYb3sWa3gLz+/gqU4gGGaTOalnoP9V3MqfbNn4nn0+lKOXIIzqhHvNi7Ao/FYJfeIZSUY2r3K0UJfamTBP2lc33zPJOUU22zQX1PNskS4n3LogHHUuNGjlSIJp2irY7AIe8fz+sVn/8wDqwaldapNR/NUnMigcVfLsmGOPGe+MxlvMIkXrxXyCS5DSN35x2V72BsjPOIruUHGj6Uvg/j+0MOyVCgYG8Dv0/gFOHn9rmo8Nb2plIsoHi3dVoptX6nK0z1CVJLYk3aZBMCasfVsE4d0yGol2K+B/If1O1BLvY6bXU13PABfFnJETQWHwCxPcvVwRWiykB6qSVGMSeDVVLPMvK/XItw6h40SOHecRKGhuZyiHPgIRIbpS4XtTc9eMfGaKmUcswS/yrVMixzVWbamhHqjW2taZvUd1dTPO2WNzcg+GfldiLp45MAucIdArgd7oMRHE0Do9tBenokNA8JOcQARfgJQ1wg5qisSGyV3OG6nNpPpI+ud+gmrVCCpeVntCvCJL27y6onzESUJaBQYisItaJ/upoYormB/namhTAH50M8zywZ8aBi7Igx3TXQbUCB/Q8IXWNSJf+NKj9WpIWzOgFrtgF0bVnpZZmCdlhQJyXPWqBtfbOn0A5toCXxiU+73FuJJBBb2NXqHTh/XPWissh15bV+Pb6tWKlzKpYFuGltbRzlU7/myalOTQIjfxKydyVI7mGQ+
  template:
    metadata:
      name: ghcr-secret
      namespace: baskit
    type: kubernetes.io/dockerconfigjson

