apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault-backup
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-backup
    app.kubernetes.io/instance: vault
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backup
  namespace: vault
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: vault-backup-storage
          serviceAccountRef:
            name: external-secrets-vault-backup
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-backup-s3
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backup
  target:
    name: vault-backup-s3
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: services/object-storage/vault-backup
        property: access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: services/object-storage/vault-backup
        property: secret_key
    - secretKey: AWS_ENDPOINT_URL
      remoteRef:
        key: services/object-storage/vault-backup
        property: endpoint
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: services/object-storage/vault-backup
        property: region
    - secretKey: AWS_BUCKET
      remoteRef:
        key: services/object-storage/vault-backup
        property: bucket
