apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - helm-repo.yaml
  - helm-release.yaml
  - tls-certificate.yaml
  - vault-ca-cert-configmap.yaml
  - backup-external-secret.yaml
  - backup-cronjob.yaml
  - backup-prometheusrule.yaml
