apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls-cert
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - vault.vault.svc.cluster.local
    - vault.vault.cluster.local
    - vault.cosmos.cboxlab.com
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: ECDSA
    size: 256
