{
 "title": "Restic Backups",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo",
    "label": "Repo",
    "query": {
     "query": "label_values(restic_repo_stats_snapshots_active,repo)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Snapshots Count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(repo) (restic_repo_stats_snapshots_active{repo=~\"$repo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Bucket Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(repo) (restic_s3_size_total{repo=~\"$repo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time since last Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() -  max by(repo) (restic_repo_last_snapshot{repo=~\"$repo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Object Count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(repo) (restic_s3_object_count{repo=~\"$repo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refresh failures",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(repo) (rate(restic_repo_stats_refresh_fail_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Bucket Size %",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(repo) (restic_s3_size_total{repo=~\"$repo\"}/restic_s3_size_limit{repo=~\"$repo\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}