apiVersion: v1
kind: Service
metadata:
  name: intel-vllm
  labels:
    app.kubernetes.io/name: intel-vllm
    app.kubernetes.io/instance: llm-serving
    app.kubernetes.io/component: inference
    app.kubernetes.io/part-of: llm-serving
spec:
  selector:
    app.kubernetes.io/name: intel-vllm
    app.kubernetes.io/instance: llm-serving
  ports:
    - name: http
      port: 8000
      targetPort: http
