apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agent-router-crds
  namespace: envoy-ai-gateway-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: agent-router-crds
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
