apiVersion: v1
kind: Service
metadata:
  name: llm-serving-metrics
  labels:
    app.kubernetes.io/name: llm-serving
    app.kubernetes.io/instance: llm-serving
    app.kubernetes.io/component: monitoring
spec:
  selector:
    component: predictor
  ports:
    - name: metrics
      port: 80
      targetPort: 8080
      protocol: TCP
