apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huggingface-cache
  labels:
    app.kubernetes.io/name: huggingface-cache
    app.kubernetes.io/instance: llm-serving
    app.kubernetes.io/component: model-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
