apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve-localmodel-crd
spec:
  interval: 1h
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: kserve-localmodel-crd
  dependsOn:
    - name: kserve-crd
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
