apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kserve

resources:
  - oci-repositories.yaml
  - helm-release-crds.yaml
  - helm-release-resources.yaml
  - helm-release-runtimes.yaml
