apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: psuite
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: psuite
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: psuite
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: psuite-wiki-creds-vault
  namespace: psuite
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: psuite-wiki-creds-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: creds
      remoteRef:
        key: apps/psuite/wiki
        property: creds
