apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: shoppinglist
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: shoppinglist
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: shoppinglist
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shoppinglist-config-vault
  namespace: shoppinglist
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: shoppinglist-config-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: services/postgresql/shoppinglist
        property: password
