apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: beancount
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: beancount
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: beancount
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fava-auth-vault
  namespace: beancount
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: fava-auth-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: auth
      remoteRef:
        key: apps/beancount/auth
        property: auth
