apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: litellm
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: litellm
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: litellm
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets-vault
  namespace: litellm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: litellm-secrets-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: apps/litellm/core
        property: master_key
    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        key: apps/litellm/core
        property: salt_key
    - secretKey: DATABASE_URL
      remoteRef:
        key: services/postgresql/litellm
        property: database_url
