apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: litellm
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/instance: litellm
spec:
  type: oci
  interval: 1h
  url: oci://docker.litellm.ai/berriai
