apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: qwen
  labels:
    app.kubernetes.io/name: llm-gateway
    app.kubernetes.io/instance: llm-gateway
spec:
  endpoints:
    - fqdn:
        hostname: qwen2-5-7b-instruct-rocm-predictor.llm-serving.svc.cluster.local
        port: 80
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: qwen
  labels:
    app.kubernetes.io/name: llm-gateway
    app.kubernetes.io/instance: llm-gateway
spec:
  schema:
    name: OpenAI
    version: v1
  backendRef:
    group: gateway.envoyproxy.io
    kind: Backend
    name: qwen
