apiVersion: v1
kind: ConfigMap
metadata:
  name: portkey-intel-llama-request-headers
  labels:
    app.kubernetes.io/name: portkey
    app.kubernetes.io/instance: portkey
    app.kubernetes.io/component: gateway
data:
  X-Portkey-Config: '{"provider":"openai","api_key":"not-used"}'
  X-Portkey-Custom-Host: http://intel-llama.llm-serving.svc.cluster.local:8080/v1
