apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portkey

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - intel-llama-ingress.yaml
  - request-headers.yaml
  - intel-llama-request-headers.yaml
