apiVersion: v1
kind: ConfigMap
metadata:
  name: portkey-request-headers
  labels:
    app.kubernetes.io/name: portkey
    app.kubernetes.io/instance: portkey
    app.kubernetes.io/component: gateway
data:
  X-Portkey-Config: '{"provider":"openai","api_key":"not-used"}'
  X-Portkey-Custom-Host: http://smollm2-135m-vllm-predictor.llm-serving.svc.cluster.local/v1
