apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: amd-gpu-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: amd-gpu-device-plugin
    app.kubernetes.io/instance: amd-gpu-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: amd-gpu-device-plugin
      app.kubernetes.io/instance: amd-gpu-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: amd-gpu-device-plugin
        app.kubernetes.io/instance: amd-gpu-device-plugin
    spec:
      priorityClassName: system-node-critical
      nodeSelector:
        homelab.cboxlab.com/gpu: amd
      tolerations:
        - key: homelab.cboxlab.com/gpu
          operator: Equal
          value: amd
          effect: NoSchedule
      containers:
        - name: device-plugin
          image: docker.io/rocm/k8s-device-plugin:1.31.0.9
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: device-plugins
              mountPath: /var/lib/kubelet/device-plugins
            - name: sys
              mountPath: /sys
              readOnly: true
      volumes:
        - name: device-plugins
          hostPath:
            path: /var/lib/rancher/k3s/agent/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
