---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordle
  template:
    metadata:
      labels:
        app: wordle
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: modem7/wordle:latest
        imagePullPolicy: IfNotPresent
        name: wordle
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
      restartPolicy: Always
