apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
spec:
  interval: 1h
  url: https://helm.openwebui.com/
