apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault-firebase
  namespace: baskit
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-firebase
  namespace: baskit
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: baskit-firebase
          serviceAccountRef:
            name: external-secrets-vault-firebase
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: baskit-metrics-firebase-vault
  namespace: baskit
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-firebase
  target:
    name: baskit-metrics-firebase-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: firebase-credentials.json
      remoteRef:
        key: services/firebase/baskit
        property: service_account_json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: baskit-backup-firebase-vault
  namespace: baskit
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-firebase
  target:
    name: baskit-backup-firebase-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: firebase-credentials.json
      remoteRef:
        key: services/firebase/baskit
        property: service_account_json
