---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: baskit
spec:
  encryptedData:
    .dockerconfigjson: AgA3CGy+ukr8VYpUMSXIis0QXK9kbOWVYFd68gCg0nRGun3co4nTYMf/wGxgp39FPM04T6kpTXor6TG6bIAwzwYNBK9hkApjEULkrp4eh6M3KBxfM3nz91aDDuSOE0ypR324hRrwLYo8Xvd5GU4rh4P+kQFCfnTO78Aiu4PT9ls4RSQ1hfOjbI/jklZy/pAAp++1Z58rQqfS69PZcRwAvlKrQgDC4AAZVL1ZaorNsTRSHhT/EwqgzOhRxsu91gsoSubZWX9CKn5Z29qKFJlHTHHqZrS9bNSMtuUZ0qCSZQLIzM69h1IqczgJlMabq71T+L9rcIQ68syrq9nvfHskB0lU3ktNmb0SmmrUYg99QQthOvN+4hpsXa/knekL0L+f9S7DWnfLPSGPqpAOnC2Ya44rl5oKngmXSWSupjjoUu938hbf/+Awqym2DI0+dz8LXL9eSneKy1zoEyiIXMnGq5ZW1PMXE1SKPV9YYQ/tWVa0hnvANMaN1I/FwljIUccpMU1u59ao90Tyn9VOSSbBA0MdbaC9+3JY4c5YgRIgpFBreQ4tTkOWLeOTa2XmnhUdJDYUPhcjxK56G6Unc6UOsV+kZ/3le30n3u2P+hbJgmiHO95iC7ARN1EtRCcC166kFLaGEbiQQXaX57F2jo4/fCz7dSZK22lp3u8KuM6JNfqN/bA2M/9KftT2r13eIcjaiyV9Z/jtLZkYJTnPP4Y//0XXMrrBhu+w5ic3n+GfBFcccB+lg6EZc2FtETsnDUGU290Z0eHGYVZT2XZ7QCMkknTQg0w7wgRlozh34lgteXnDeQ55O96+59UCa45yFHCprLedS7rdxIqqxXMmPM+xwvt5XZnb62ESLunRgLLt3l1k9xrh8OqVcMLQXg==
  template:
    metadata:
      name: ghcr-secret
      namespace: baskit
    type: kubernetes.io/dockerconfigjson

