---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: baskit
spec:
  encryptedData:
    .dockerconfigjson: AgCwDVKg94YT4j9nzRDGz860p2o4AvG32c9+OXn3NOKWgbLgziTMxhxJEaKoQswF1zx6XIEeG7E4gksES3PDl4e1bi3u00xH8dzZ9/2M2nKiXJnK6FDMW5suOVxX4ZSQMD0JM4bfi2a8wI273kJLWMe6OFurAEi/jUW4NqLC04U5DL3Yvidi59za7wLLsf5eSeLbOmbk3tuavsKolV60zBYXhL7lQjBVgWC6Bt3pAusBK4yG0dHn0jZxdfvU3RD1qH8q159bnrAY7ENh4xHMpDXZ8JgKuwWGIsI9J6hdtuM6jvoUsUnbYJEsVtRuh9hKYVQYIAQTMR353MB/8I2kANXGL06iy6JqE7h2nh1KJXG7tYjMMjh4ey2BDD3XlhTvHTPJZjJdvy/N4oWVXuOBF1Ggo3wclrbJCNDbiCG9643Df5ukib69PyB2hUX2Y6D0jrceYhInU+sFTkOKWTL8ZeJkRnNrMc3AKhSZEreRrZqojcP2Bvzl73+XpLfuEffEOYnKJnwY6FWlCfDrTYFLn59nXv4zKtL4xmgLWgzIULdVzIxEsjXb3ByISdWZ8GiZB8WRT8pu3NKSGaT8GpdgAAZYM36qSak5TZ26rs+nsl0STziI05Ez2zPdA6HS1zCY0+LItBqw+gLpsLB0HGrvkPR3By5PjoqAWqyEx1JRE6xMdyNu5HhALff7tjlpSenGt1xzW2tvBWzh7BwZ6aFSZz5+FVSkLTdWH45FWcs85ukGxUsJyCLOkveFjogoONoCvGmLiBmbzykFJNmSoNLwqnupoQPV1T4s41EWkoNAW1Dsp12to+XWfEJxeWS3B+j1g/SxzzThb7Vuah+oQOVY2enOBu5jOF2+9U+blxYFP9JMgBJeWgtNs/aXUokpsioavVzRYMf5VoNCmK0OEjiUFrSGJRT/ApzNvQCqXXxr68sZAwwZ8795jRY9DgQrbW2z8F0ZrSLvcyAMDkr0qq5EO5b6KS9BNtlTTNljyhNpDkd5
  template:
    metadata:
      name: ghcr-secret
      namespace: baskit
    type: kubernetes.io/dockerconfigjson

