apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: glance
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: glance
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: glance
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-secret-vault
  namespace: glance
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: glance-secret-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ADGUARD_PASSWORD
      remoteRef:
        key: services/adguard/glance
        property: password
    - secretKey: IMMICH_API_KEY
      remoteRef:
        key: services/immich/glance
        property: api_key
