apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: dotbintask
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: dotbintask
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: dotbintask
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dotbintask-secret-vault
  namespace: dotbintask
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: dotbintask-secret-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: tokens
      remoteRef:
        key: apps/dotbintask/api
        property: tokens
