apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: wallabag
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: wallabag
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: wallabag
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-config-vault
  namespace: wallabag
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: wallabag-config-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SYMFONY__ENV__SECRET
      remoteRef:
        key: apps/wallabag/core
        property: app_secret
