---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wallabag-config
  namespace: wallabag
spec:
  encryptedData:
    SYMFONY__ENV__SECRET: AgCiqzFvdGZ+fDkilxTG4MZPZeU7qm6zwBPVp+T/EKhLkw9aSGzylrxoicdWvVy5dYmaz1XNTbA4xOkeC55QyVFUHaBcaoTY+NM4oTlD4eTcA+P02zum3AhfZNvIe2+tryZYK0snpobMLSdx+3jV0Fbk8uPyhXABg6j2M57NOyT6bmuTz6RXaxZcuGnera6hBzgCw6LjOBTom1ULS/NmvFjXP4t8yHvRC40SK81iIkHq3qfWw78pmBIGuib2z1kOdDOiNVHRC0zkDcqPSu/vB2ZpR8+VfwY3PkYmhcaAj7fwaMYwQAoJpF7d8GZL1XWYxMUenXSn4CCV6GBVlH2EmHJRDS4lMVOiVBtlcCUQy/3EqhsmEb9YBEBF//AvKf75wwiFcT1jE5gKThAiJHzwAFgAQXDxSN6TGketHKqWwMXeEVklxA0sBvgE5C8TMLWjbm+trKpYFN/FqUVU98tRf2xIkuaa0Vy8HXbeT7YKWUqY9qrYEBmZ/EEx0WhPrW+igs+OvfNAgHv+hV68qzcA2bPrbiPDsFeSkkY/o3YuNnCqkLe/dj85rnjxNfCDDGhvASul5S0zjGlZQD24m4yF4987N4u/PRY+OJsbHI2iShIFJ+bwkQcVNCLT5mvYsIHLVIcv9quBHS8kWp6EFIE3a8mLWBqaX4F3wmUdIuIKLyEzLcGIVTSBwITILrfoVLabf+CHjGbY6ZPQDhSu1HKF5YTGSzkBjctarkB1Kpex/oLJhs53/vtKOp6bPuZ4eZyovIsVy+XcdVJVTvBzn80ZEOEr
  template:
    metadata:
      name: wallabag-config
      namespace: wallabag
