#!/usr/bin/env node
import { mkdtemp, readFile, unlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { PiAgentAdapter } from "./agent.js";
import { loadConfig } from "./config.js";
import { changedFiles, repositoryRoot } from "./git.js";
import { createRun, findRun, loadManifest } from "./state.js";
import { Workflow } from "./workflow.js";

interface Args { command?: string; positional: string[]; options: Record<string, string | boolean> }
function parse(argv: string[]): Args { const result: Args = { positional: [], options: {} }; const command = argv.shift(); if (command) result.command = command; const known = new Set(["requirements-file", "editor", "config", "decision", "feedback-file", "requirements", "artifact", "yes", "help", "non-interactive"]); while (argv.length) { const value = argv.shift()!; if (!value.startsWith("--")) { result.positional.push(value); continue; } const name = value.slice(2); if (!known.has(name)) throw new Error(`Unknown option: --${name}`); if (["editor", "requirements", "yes", "help", "non-interactive"].includes(name)) result.options[name] = true; else { const next = argv.shift(); if (!next || next.startsWith("--")) throw new Error(`Missing value for --${name}`); result.options[name] = next; } } return result; }
async function editorRequirements(): Promise<string> { const directory = await mkdtemp(path.join(os.tmpdir(), "autonomous-agent-")); const file = path.join(directory, "requirements.md"); await writeFile(file, "# Requirement\n\n", { mode: 0o600 }); const editor = process.env.VISUAL || process.env.EDITOR; if (!editor) throw new Error("Set VISUAL or EDITOR, or use --requirements-file"); await new Promise<void>((resolve, reject) => { const child = spawn(editor, [file], { stdio: "inherit", shell: false }); child.on("error", reject); child.on("close", (code) => code === 0 ? resolve() : reject(new Error("Editor exited unsuccessfully"))); }); const content = await readFile(file, "utf8"); await unlink(file); return content; }
function help(): void { console.log(`Usage: autonomous-agent <command> [options]\n\nCommands:\n  start    --requirements-file <path> | --editor [--config <path>] [--non-interactive]\n  resume   <run-id> [--decision approve|revise|reject|pending] [--feedback-file <path>]\n  status   <run-id>\n  inspect  <run-id> [--requirements] [--artifact <relative-path>]\n  smoke    [--config <path>]\n`); }
async function confirm(question: string): Promise<boolean> { const terminal = createInterface({ input: stdin, output: stdout }); try { return (await terminal.question(`${question} [type yes]: `)).trim() === "yes"; } finally { terminal.close(); } }
async function main(): Promise<void> {
  const args = parse(process.argv.slice(2)); if (!args.command || args.command === "help" || args.options.help) { help(); return; }
  const repo = await repositoryRoot(process.cwd()); const config = await loadConfig(repo, typeof args.options.config === "string" ? args.options.config : undefined); const adapter = new PiAgentAdapter(); const interactive = Boolean(process.stdin.isTTY && process.stdout.isTTY && !args.options["non-interactive"]); const workflow = new Workflow(repo, config, adapter, interactive);
  if (args.command === "smoke") { await adapter.verify(config); console.log("All configured models are available; no session or repository mutation occurred."); return; }
  if (args.command === "start") { const file = args.options["requirements-file"]; if ((typeof file === "string") === Boolean(args.options.editor)) throw new Error("Choose exactly one of --requirements-file or --editor"); let requirements: string; if (typeof file === "string") { try { requirements = await readFile(path.resolve(file), "utf8"); } catch { throw new Error("Requirements file is missing or unreadable"); } } else requirements = await editorRequirements(); if (!requirements.trim()) throw new Error("Requirements cannot be empty"); const manifest = await createRun(repo, config, requirements); console.log(`Run created: ${manifest.runId}`); await workflow.execute(await findRun(repo, config, manifest.runId)); console.log(`Run ${manifest.runId} is awaiting human approval.`); return; }
  const runId = args.positional[0]; if (!runId) throw new Error(`${args.command} requires a run ID`); const directory = await findRun(repo, config, runId); const manifest = await loadManifest(directory);
  if (args.command === "status") { console.log(`run: ${manifest.runId}\nstate: ${manifest.state}\nupdated: ${manifest.updatedAt}\niterations: plan=${manifest.iterations.plan}, implementation=${manifest.iterations.implementation}, governance=${manifest.iterations.governance}\nusage: input=${manifest.usage.input}, output=${manifest.usage.output}, turns=${manifest.usage.turns}`); return; }
  if (args.command === "inspect") { if (args.options.requirements) console.log(await readFile(path.join(directory, "requirements.md"), "utf8")); else if (typeof args.options.artifact === "string") { const requested = args.options.artifact; if (path.isAbsolute(requested) || requested.includes("..")) throw new Error("Invalid artifact path"); console.log(await readFile(path.join(directory, "history", requested), "utf8")); } else console.log(await readFile(path.join(directory, "manifest.yaml"), "utf8")); return; }
  if (args.command === "resume") { if (manifest.state === "failed") { console.log("Failed runs retain their artifacts. Inspect the failure before deciding on a manual recovery."); return; } const publicationRetry = ["commit_and_push", "create_pull_request", "record_pull_request_metadata"].includes(manifest.state); if (manifest.state !== "awaiting_human_approval" && !publicationRetry) { console.log(`Run is ${manifest.state}; no action is required.`); return; } const decision = args.options.decision; if (!decision || decision === "pending") { console.log("Run left pending; no Git or remote mutation occurred."); return; } if (decision !== "approve" && decision !== "revise" && decision !== "reject") throw new Error("--decision must be approve, revise, reject, or pending"); if (publicationRetry && decision !== "approve") throw new Error("Publication retry requires --decision approve to preserve the recorded approval"); if (decision === "revise") { const feedbackFile = args.options["feedback-file"]; if (typeof feedbackFile !== "string") throw new Error("--decision revise requires --feedback-file"); const feedback = await readFile(path.resolve(feedbackFile), "utf8"); if (!feedback.trim()) throw new Error("Revision feedback cannot be empty"); await workflow.requestRevision(directory, feedback); console.log("Revisions completed and returned to the human approval gate."); return; } if (decision === "approve") { const paths = await changedFiles(manifest.worktree!); console.log(`Proposed commit: feat(agent): complete autonomous run ${runId}\nProposed PR target: main\nPaths:\n${paths.map((item) => `  ${item}`).join("\n")}`); if (!args.options.yes && !(await confirm(publicationRetry ? "Resume the approved publication?" : "Commit, push generated branch, and create a PR?"))) { console.log("Approval cancelled; run remains pending."); return; } } await workflow.approveAndPublish(directory, decision); return; }
  throw new Error(`Unknown command: ${args.command}`);
}
main().catch((error: unknown) => { console.error(`Error: ${error instanceof Error ? error.message : "unknown failure"}`); process.exitCode = 1; });
