apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: external-dns
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: external-dns
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-dns-cloudflare
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-creds-vault
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: cloudflare-creds-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api_token
      remoteRef:
        key: services/cloudflare/dns-cboxlab
        property: api_token
