apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: torrents
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: torrents
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: torrents
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openvpn-config-vault
  namespace: torrents
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: openvpn-config-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: auth.conf
      remoteRef:
        key: services/vpn/deluge-openvpn
        property: auth_config
    - secretKey: config.ovpn
      remoteRef:
        key: services/vpn/deluge-openvpn
        property: client_config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wg-config-vault
  namespace: torrents
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: wg-config-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: wg0.conf
      remoteRef:
        key: services/vpn/deluge-wireguard
        property: client_config
