---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wg-config
  namespace: torrents
spec:
  encryptedData:
    wg0.conf: AgCWLQ8gqKNjKGgQl19IQK4chVB26LbP5RIxKqWNYXLPunMD2NCTsUgTFFkxp9h2bwbgU8rT/MfzEkL2KKqbb6mWkIxnyHgya6LHCuXh5IkSXu1IVTOMaRt95iSEdVYKQweirR/8nHlXPTckgp9XzTbpEj9NiXOOQz1HbDzHmTDPW6Jk/bHulsQWQITcIUyqbSWG1SGIgMcpNXtpkaIWdPFXIzNuaFbqaB8AWKLohxIt+1AapSYwpMyzllauGF1xHLtnm2oqEp9hYK9IfQAt3KSaSwoPwWfI2+r6pe2CJhNmJftRSF10CmHs938uK1OUXUyyCyk/E8ncw0av/lgMW8m3WvOHCVxGhnNb+C3q2pkLX6HoIp+QDBUp4WCxAF8XIcrWHkZTlAc8/pv2SF0tOV74+xIlKXnXG9J94IPP5LKlASx9ufrJVq5dqvQjjWWZX1L0PHjtZgr5ocas/MiEDGwWW5gKryDDv/rnMw00sUsKCM106oKSRVVDOgD3qhfnJspNeh9Bp7bDoOuZt23D773xqtcYjMWM4C0uDX4GNJL7iX6aCW1Y7V8gLeTi9o8gg1A23Own/qJFqL4qWlf0+DDr8Hv0A6DeJkf5Ppb9nWzj98l19Nd6FRko7DW9ExScUgSEV2VHmGtciEsm2aexKKiPCJDRSFGOjc/m85v7EkespO3uYXFuzuDk1FlVCMklg3iYB4VDAog84Umz/WgNJvGgayL3VmJ0Y7ZmWdAsPZhWRiZdQQgyoCxPk89qhK4H0Unoz9Lim7CsuLD6kxx2W1Jyo+faHCGrsNyFXhgRyRp/+DWcEJ7PUuCEGupq0jVfK5YJJqNeMbX85pFVdvI2NEGg8kiu/bStOy9cKcvhoqSosuQBiC7uPZrNUiayQ3qSu2x2QHwjE+RfNd7Wy3Xoy4Od6b9RRuCc9Njd6any9DXlZFNjj77YrNBswPnOypYhi+qrDuVClUeGf6dAKpXcOKdymEUtR2MmqAFBxZRrWpgt/QzNYhrkEhejzuJfF8Ms31gnd3gfknOf7SFNwyds2l+ZbVyYYK8+DiaKa6J7y3ezN/znDedUZ1un7/gTJz8EZB4=
  template:
    metadata:
      name: wg-config
      namespace: torrents

