---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wg-config
  namespace: torrents
spec:
  encryptedData:
    wg0.conf: AgAmQZb3gyVkEFyZJJdAhwLkEfSPrEWuFm4kQtEyfmK/3PtyJ82qSR5ubbYHEtiEdLOb0DIL07mbpzbDXGdn4O/lVpoIb3JlMUZn1+3vuhg0ppwLA3ymiaDR/byxuXJiEGU/S0z9HBM9Iix81JIkh5GMBo+L6OdX7kElohmy7GhXChHhEh+stZ3yiFPSGD8k1sF6NrqUnBjbGyuMeEjXmfInAbxCy2NfuWhsoUndTg1pVqixwhcEGOQIhrCM4uLCQnvAcmTvKDTprPKVozkzzJ5n9/wffXUTGkmGNO9PynLXmbpfCZONE+DF9k1OHirETtfXiD5I6zbSZAyW6/oe7HrqhkeNQGfMUV0+6usDhTuIf4SR9RszAqtzZoSbEH5Ch6gWLmL8IKYL1qsIBfVBIG05A7t/sddBcQFGyxJSlZZ5LKu9yY+zJAeXEu4VLmpTndA/RbF4GSjYFZ3Ut6/H+fxlqVCM8zB4k2L8360zXqcvkArKlsi3c9iBBhmkJnQjIAM7EjCr4uEKT4CEMCKpfCjXfab14kdIDq70rTyElMrPLZCfk4+7S8KnJ1L+JpVS+6QyjylAtjzksJgTuQFsRf0L0hcmRTvFs1CgG6kAZivhf07rNHvlFKbQEBd8VvGQ2awUzPiv1vmxg4dosEHHsbCtjT8qPUAmaan2XcItBkiInWTTq2TOFIkLmDUqQganNjm3k1oECE4E5+WjshsxjnpBWNt1QZpjr5VOYuG7dGmU53Vi6zd33VJq1DuE+Nqa3iQOYsbATg7vzoWAU2zirgVBdcBxoaGm9vhxDJuARKWV9ZnGYbOM9Vo/Nqrxoylr4TZPas6hrI8Zquh7GWjcNXMOszoclQoEI9nfiaXq2RU9aZVHXdf06/8KS6ErXDNl9Z5+/c3P7jZsMTKxN6sNcNnNe7duBOz9qUktpT5MyAdKXQZWjhFQWSSMBICDoh45k9x7dgOUIRL/Kyo1hbmYs6rQeybnVanupmXr4ASAKiOg324BqZxcuSLsFRroCz7G3037XrM1/Pjj9U87w910bG78
  template:
    metadata:
      name: wg-config
      namespace: torrents

