---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wg-config
  namespace: torrents
spec:
  encryptedData:
    wg0.conf: AgB/JE91U7RuJqFL2HgxzLIiU8Xo5TV6PWq4pu1WbDo82iJKpasf65nvqbVSaYNgC0jMFoX/br0AvPVvqiuNmtutl5VFI4l+wRGqKpcX2wEdpw7reSFP3i/GcXzhuGsSRaKlJi8SUllKeKRA4QF2DoXnvqffc6SJYGJV6Kbp4tajd2552lPqBiVJwkOhD2XtY91jbpiMhcPehjz8kfCXbw1InqF/aEF1pTSrUNlJIBtkvI69qwbh+NeqVzy0hKTQ0AUZkKrO/F2jlgjB5zALgzGhL3xPrOcPoipBlSbsqGW1IYYHA01jE2cKWctcdxfoYuhIH3g8uE+mKn8U1FDDGQSfHzeHbIcT4pJTUkRVJi54IoTncmOaMelxJgk4s/VryY6JyUGeeAoorL1SlLGtrbfUPNSz9sbNl8EA8xxpygTgzFM5uaZkg0FgILhpPtWQSxOtsGjMaUBWLj7Q7mXQrVaXHsK07hF4kp/xNJdyF/nH2m4z4UvRQks7YcsdBu4Qv+PlsDHF71bBGew0VvId/gUbPmvFD+eduIeRypm7943M+zN7GEQh0ON+0/epduZ0euNxK1Tv5PI7yrrpRuTn3UVbKvY2AraJd66Uv7u7Q4RQlhOVrS4Fa6J+O0AaqOn9p6SwzocYC7ivaaDkv08rq1hHdMBnGtM2G3U8ciJPNS/h2C+HSRwRfGS1hxrzUxTo6576EBI1jS5nNrSZ2lqMubd6qj3JQTN9Y1MZ8Asw9es0Z32TUK1FHdG3YrZyd3u2SuNblk5BopoK9zaQQe+dgxpBfTzs/m7xF3ugUX+EEgFWY6xQVbjwZ8NpFgE+FOGYIELZy75fg2A1zAKAR0rJIpw9Qfr4XJKCtvgkDSjx7DihUcxlWzYOOmUxvcv561L1ZWpTf9I3ZAOmztWhKut13CrLweaQMWOw26yR5ZCR/0K2cG/G8AZHoTys5yA1nepZEByzDwWJlqATbHtpgYEIYRroom0Cc7J64XUdp/j2gQ/Bqh+zj7ACc3EvF/5lLUxP4M9AobA4jiNNUI3tVzjUEg0eCCYGdckoG0udSrP+13HvJzEu+J01Kk7FuLoqySfUog==
  template:
    metadata:
      name: wg-config
      namespace: torrents

