apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault
  namespace: totp
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: totp
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: homelab/kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: otpcloud
          serviceAccountRef:
            name: external-secrets-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otpcloud-secret-vault
  namespace: totp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: otpcloud-secret-vault
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: apps/otpcloud/core
        property: app_key
    - secretKey: DB_CONNECTION_STRING
      remoteRef:
        key: services/postgresql/otpcloud
        property: connection_string
